LinkedList: main_LinkedList.cpp LinkedList.hpp Node.hpp
	g++ main_LinkedList.cpp -o LinkedList
VideoShare: main_VideoShare.cpp VideoShare.cpp VideoShare.hpp Video.cpp Video.hpp User.cpp User.hpp LinkedList.hpp Node.hpp
	g++ -g main_VideoShare.cpp VideoShare.cpp Video.cpp User.cpp -o VideoShare

